/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: (typeof import("./../App.vue"))["default"]
    ButtonItem: typeof import('./../components/form/ButtonItem.vue')['default']
    ChatContext: typeof import('./../components/ChatContext.vue')['default']
    ChatNavbar: typeof import('./../components/ChatNavbar.vue')['default']
    ForgePwdContent: typeof import('./../components/ForgePwdContent.vue')['default']
    'IconAntDesign:settingOutlined': typeof import('~icons/ant-design/setting-outlined')['default']
    'IconPh:moon': typeof import('~icons/ph/moon')['default']
    'IconPh:sun': typeof import('~icons/ph/sun')['default']
    'IconTdesign:setting1': typeof import('~icons/tdesign/setting1')['default']
    'IconUil:setting': typeof import('~icons/uil/setting')['default']
    InputItem: typeof import('./../components/form/InputItem.vue')['default']
    LayoutItem: (typeof import("./../layouts/LayoutItem.vue"))["default"]
    LoginContent: typeof import('./../components/LoginContent.vue')['default']
    LoginPage: (typeof import("./../views/LoginPage.vue"))["default"]
    Register: (typeof import("./../components/register.vue"))["default"]
    RegisterContent: typeof import('./../components/RegisterContent.vue')['default']
    RegisterPage: (typeof import("./../views/RegisterPage.vue"))["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./../components/SettingItem.vue')['default']
    SwitchLanguage: (typeof import("./../components/form/SwitchLanguage.vue"))["default"]
    SwitchTheme: (typeof import("./../components/form/SwitchTheme.vue"))["default"]
    ToggleDarkMode: typeof import('./../components/settings/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./../components/settings/ToggleLanguage.vue')['default']
  }
}
